### ISSUE TITLE
The server sends no emails on server errors anymore

### ISSUE THREAD

**Issue by frankystone** [widelands/widelands-website#363]
Recently we had a map with an `ß` in his name, which can't be downloaded (#332), instead the user get prompted with a white error page saying "Internal server error".

Before around Oktober the user get prompted with an error page in website style (not a blank page) and admins get informed about such issues with an email so they can react. Since around Oktober 2021 no emails were send anymore and so the map with 'ß' in his name causing server errors wasn't noticed by the website admins.

I talked with janus about this and he tried to find out what the cause of not sending emails may is. Without success so far. But he got an error from gunicorn:

~~~~
Dec  4 17:48:08 widelands gunicorn[3441]: [2021-12-04 17:48:08 +0100] [8305] [ERROR] Error handling request /maps/boer-name/download/
Dec  4 17:48:08 widelands gunicorn[3441]: Traceback (most recent call last):
Dec  4 17:48:08 widelands gunicorn[3441]:   File "/var/www/django_projects/wlwebsite/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 135, in handle
Dec  4 17:48:08 widelands gunicorn[3441]:     self.handle_request(listener, req, client, addr)
Dec  4 17:48:08 widelands gunicorn[3441]:   File "/var/www/django_projects/wlwebsite/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 182, in handle_request
Dec  4 17:48:08 widelands gunicorn[3441]:     resp.write(item)
Dec  4 17:48:08 widelands gunicorn[3441]:   File "/var/www/django_projects/wlwebsite/lib/python3.6/site-packages/gunicorn/http/wsgi.py", line 333, in write
Dec  4 17:48:08 widelands gunicorn[3441]:     self.send_headers()
Dec  4 17:48:08 widelands gunicorn[3441]:   File "/var/www/django_projects/wlwebsite/lib/python3.6/site-packages/gunicorn/http/wsgi.py", line 329, in send_headers
Dec  4 17:48:08 widelands gunicorn[3441]:     util.write(self.sock, util.to_bytestring(header_str, "ascii"))
Dec  4 17:48:08 widelands gunicorn[3441]:   File "/var/www/django_projects/wlwebsite/lib/python3.6/site-packages/gunicorn/util.py", line 507, in to_bytestring
Dec  4 17:48:08 widelands gunicorn[3441]:     return value.encode(encoding)
Dec  4 17:48:08 widelands gunicorn[3441]: UnicodeEncodeError: 'ascii' codec can't encode characters in position 182-183: ordinal not in range(128)
~~~~

@stonerl ?
@SirVer ?

**Comment by frankystone** [comment]
On alpha an old [map with certain special characters](https://alpha.widelands.org/maps/sonderzeichen-aous/) can be downloaded without problems (except the name isn't proposed). A newly uploaded map with name [Bößer Näme](https://alpha.widelands.org/maps/boer-name/) gives an server error but no mail.

Database entries for both maps:

| name                                       | slug                            | file
| -------------------------------------   | --------------------------- | -------------------------
| Sonderzeichen äöüſþđøłæð↓æ←                | sonderzeichen-aous              | wlmaps/maps/Sonderzeichen_äöüſþđøłæðæ.wmf            |
| Bößer Näme                                 | boer-name                       | wlmaps/maps/Bößer_Näme.wmf                           |

**Comment by frankystone** [comment]
There were no error mails because there was no error in our django code. Instead the server error occurred inside gunicorn.
